unique_ids:
  forms:
    Form1: EBHGYXCO6RO4H5LUM3IVS4LZNYQIOCNY
  modules: {}
  server_modules: {}
  assets:
    3mhYtd3.png: '1708335216101862152087953.4032'
    standard-page.html: VNUEB7CFUF6CVT6M3W7BDRJKJW46JYMS
    theme.css: GGTMZCBKI6J5T4UGBXLSOOXGTSR2XAEL
    tải xuống.png: '1706690838684520493072585.6618'
